xcodeproj 'PI_NRemoteImage.xcodeproj'

def shared_pods
  pod "PI_NRemoteImage", :path => "../../"
  pod "PI_NRemoteImage/WebP", :path => "../../"
  pod "PI_NRemoteImage/PI_NCache", :path => "../../"
end

target 'PI_NRemoteImage' do
  shared_pods
end
