from .messagesdatabase import MessagesDatabase
from .usersdatabase import UsersDatabase
from .friendsdatabase import FriendsDatabase
from .postsdatabase import PostsDatabase

MessagesDatabase.deleteDatabaseFile(MessagesDatabase)
UsersDatabase.deleteDatabaseFile(UsersDatabase)
FriendsDatabase.deleteDatabaseFile(FriendsDatabase)
PostsDatabase.deleteDatabaseFile(PostsDatabase)
