source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
target 'Sample' do
  pod 'Tex_ture/IGListKit', :path => '../..'
  pod 'Tex_ture/PI_NRemoteImage', :path => '../..'
  pod 'Tex_ture/Yoga', :path => '../..'
  pod 'Weaver'
end
